#!/usr/bin/env python3
# =============================================================================
#  gen_live_pins.py  ·  v1.0  ·  Session 183
#
#  Builds `live_pins.txt` FROM the KB Register's live-file table.
#
#  WHY IT IS GENERATED, NOT HAND-WRITTEN
#  -------------------------------------
#  A hand-kept second copy of the pins would drift from the Register, and a
#  record that quietly disagrees with another record is precisely the fault
#  this whole exercise exists to close (F-97), and precisely what D202 warns
#  about. So there is exactly ONE authored source -- the Register table -- and
#  the pin list is derived from it. Re-run this whenever the Register changes;
#  the output carries the Register's filename and md5 so the checker can say
#  which record it is holding the box to.
#
#  CLASSIFICATION RULE
#     first cell is a backticked ABSOLUTE path  +  exactly one md5   -> VPS
#     anything else                                                  -> BLIND
#     a row with no md5 at all                                       -> ERROR
#
#  A row this script cannot classify STOPS the run. It is never skipped: a
#  silently dropped row is a live file nobody is checking, which is the bug.
#
#  This runs offline on the PC (or anywhere). It is not installed on the VPS.
#
#  USAGE
#     python gen_live_pins.py KB_Register_v5_4_S182.md -o live_pins.txt
#     python gen_live_pins.py --selftest
# =============================================================================

import argparse
import hashlib
import os
import re
import sys

VERSION = "1.0"

START_MARK = "## CURRENT LIVE FILE VERSIONS"
END_MARK = "## §12 STATE"

MD5_RE = re.compile(r"\b[0-9a-f]{32}\b")
TICK_RE = re.compile(r"`([^`]+)`")


def md5_of(path):
    h = hashlib.md5()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _clean(text):
    """Flatten a Register cell into one short, tab-free note."""
    text = text.replace("`", "").replace("\t", " ").replace("**", "")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def parse_register(md_text):
    """
    Pull the live-file table out of the Register.
    Returns (vps_rows, blind_rows). Raises ValueError on an unclassifiable row.
    """
    if START_MARK not in md_text:
        raise ValueError("could not find the live-file section (%r) -- is this "
                         "the KB Register?" % START_MARK)
    section = md_text.split(START_MARK, 1)[1]
    if END_MARK in section:
        section = section.split(END_MARK, 1)[0]

    vps, blind = [], []
    for lineno, line in enumerate(section.splitlines(), 1):
        s = line.strip()
        if not s.startswith("|"):
            continue
        if set(s) <= set("|-: "):          # markdown rule row
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if len(cells) < 3:
            continue
        if cells[0].lower() == "file":      # header row
            continue

        paths = TICK_RE.findall(cells[0])
        digests = MD5_RE.findall(cells[1])

        if not digests:
            raise ValueError(
                "live-file row %d has no md5 and cannot be classified: %r\n"
                "   Fix the Register, or this file goes unchecked."
                % (lineno, s[:110]))

        if paths and paths[0].startswith("/") and len(digests) == 1:
            vps.append({"md5": digests[0], "path": paths[0],
                        "note": _clean(cells[2])[:110]})
        else:
            blind.append({"md5": digests[0] if len(digests) == 1 else "multi",
                          "name": _clean(cells[0])[:60],
                          "note": _clean(cells[2])[:110]})

    if not vps:
        raise ValueError("no VPS-hashable rows found -- refusing to write an "
                         "empty pin list")
    return vps, blind


BLIND_REASON = [
    ("VPS_Push_", "Google Apps Script -- lives in Apps Script, not on this box"),
    (".gs", "Google Apps Script -- lives in Apps Script, not on this box"),
    ("migration", "an APPLIED database migration -- state, not a file on disk"),
    ("docterz_report", "PC-side file -- not on this box"),
    ("PC-side", "PC-side file -- not on this box"),
    (".service", "systemd unit -- path not recorded in the Register table"),
]


def reason_for(name, existing_note):
    for needle, why in BLIND_REASON:
        if needle.lower() in name.lower():
            return why
    return existing_note or "not checkable from this machine"


def build(register_path, out_path, session_label):
    with open(register_path, "r", encoding="utf-8") as fh:
        text = fh.read()
    vps, blind = parse_register(text)

    lines = []
    lines.append("# live_pins.txt -- generated by gen_live_pins.py v%s" % VERSION)
    lines.append("# DO NOT HAND-EDIT the VPS rows. Change the Register, re-run the")
    lines.append("# generator. One authored source (D202).")
    lines.append("# source: %s" % os.path.basename(register_path))
    lines.append("# source_md5: %s" % md5_of(register_path))
    lines.append("# session: %s" % session_label)
    lines.append("# columns: kind <TAB> md5 <TAB> path-or-name <TAB> note")
    lines.append("#")
    lines.append("# VPS    = hashed on the box and held to this md5")
    lines.append("# BLIND  = listed every run as NOT verified; never counted as a pass")
    lines.append("# IGNORE = a live file deliberately not pinned; add by hand, with a reason")
    lines.append("")
    for r in vps:
        lines.append("VPS\t%s\t%s\t%s" % (r["md5"], r["path"], r["note"]))
    lines.append("")
    for b in blind:
        lines.append("BLIND\t%s\t%s\t%s"
                     % (b["md5"], b["name"], reason_for(b["name"], b["note"])))
    lines.append("")

    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))

    return vps, blind


def selftest():
    """Prove the generator classifies correctly and refuses a row it cannot read."""
    print("gen_live_pins v%s -- selftest" % VERSION)
    checks, failures = 0, []

    def ok(label, cond):
        nonlocal checks
        checks += 1
        if not cond:
            failures.append(label)

    a = "a" * 32
    b = "b" * 32
    c = "c" * 32
    good = "\n".join([
        START_MARK + " -- table",
        "| File | md5 | live as of |",
        "|---|---|---|",
        "| `/root/app/one.py` | `%s` | S183 -- a real file |" % a,
        "| `gas/Push.gs` | `%s` | delivered, not wired |" % b,
        "| migrations `X` + `Y` | `%s` · `%s` | applied |" % (a, b),
        "| `docterz_report.py` (PC-side, tracker) | `%s` | PC |" % c,
        "",
        END_MARK,
        "| `/root/app/ignored_after_the_section.py` | `%s` | must not be read |" % a,
    ])
    vps, blind = parse_register(good)
    ok("one VPS row found", len(vps) == 1)
    ok("VPS row keeps its path", vps[0]["path"] == "/root/app/one.py")
    ok("VPS row keeps its md5", vps[0]["md5"] == a)
    ok("three BLIND rows found", len(blind) == 3)
    ok("a .gs file is BLIND", any("Push.gs" in x["name"] for x in blind))
    ok("a two-md5 migration row is BLIND",
       any(x["md5"] == "multi" for x in blind))
    ok("a PC-side row is BLIND", any("docterz" in x["name"] for x in blind))
    ok("the section END is respected",
       all("ignored_after" not in r["path"] for r in vps))
    ok("blind reasons are filled in", all(x["note"] for x in blind))

    no_md5 = "\n".join([
        START_MARK,
        "| File | md5 | live as of |",
        "|---|---|---|",
        "| `/root/app/one.py` | (to be measured) | S183 |",
        END_MARK,
    ])
    try:
        parse_register(no_md5)
        ok("a row with no md5 stops the run", False)
    except ValueError:
        ok("a row with no md5 stops the run", True)

    try:
        parse_register("nothing that looks like a register")
        ok("a non-Register file is refused", False)
    except ValueError:
        ok("a non-Register file is refused", True)

    only_blind = "\n".join([
        START_MARK,
        "| File | md5 | live as of |",
        "|---|---|---|",
        "| `gas/Push.gs` | `%s` | x |" % a,
        END_MARK,
    ])
    try:
        parse_register(only_blind)
        ok("a table with no VPS rows is refused", False)
    except ValueError:
        ok("a table with no VPS rows is refused", True)

    print("  %d/%d checks passed" % (checks - len(failures), checks))
    if failures:
        for f in failures:
            print("  FAILED: %s" % f)
        print("SELFTEST RED")
        return 1
    print("SELFTEST GREEN")
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Generate live_pins.txt from the KB Register's live-file table.")
    ap.add_argument("register", nargs="?", help="path to the KB Register .md")
    ap.add_argument("-o", "--out", default="live_pins.txt")
    ap.add_argument("--session", default="", help="label, e.g. 'S182 close'")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)

    if args.selftest:
        return selftest()
    if not args.register:
        ap.error("give me the KB Register .md (or --selftest)")

    try:
        vps, blind = build(args.register, args.out, args.session or "unlabelled")
    except (ValueError, OSError) as e:
        sys.stderr.write("\n!! %s\n\n" % e)
        return 2

    print("wrote %s" % args.out)
    print("  %d VPS rows  (hashed on the box)" % len(vps))
    print("  %d BLIND rows (listed every run as NOT verified)" % len(blind))
    for b in blind:
        print("      %-44s %s" % (b["name"], b["note"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
