#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""aaj_seed.py -- S493_LISTS_2 (parent; session 298, 07-Oct-2026). What the staff's 'Aaj ka kaam' lists START from.

PEOPLE is the owner's own mock-up, exactly as he left it on 07-Oct-2026 (claude.ai artifact 5TWb5CicYU953a2ZD4MYdW, read back
08:0x IST): who has a list, which lines, his wording, his order, which are switched on. It is only the START: once he changes
anything on his panel (/finance/aaj) the change lives in the table aaj_cfg and is laid over this file -- his word wins, this
file fills in what he has not touched. It is a .py file, not .json, because the repository's .gitignore drops *.json.

What the owner never edits lives here too, and is never taken from what a page sends:
  ENGINE     a line's working: which duty (or duties) of claude_code_briefs/DUTY_MAP.json / aaj_duties.json decide whether it
             is due ('src'; default: the duty of the same id), the page it opens when that is not the duty's own ('door' --
             '{since}' is the day of the oldest piece of that work, so the line lands on the job itself), a second line of help.
  DUE        a duty whose own SQL can never fall to nothing, re-asked for this list (see each).
  FLOOR      NOTHING BEFORE 01-OCT-2026 (the owner, 06-Oct-2026): the dated tables the floor is laid under, each with the
             expression that dates a row. aaj_kaam.py shadows each with a TEMP view on its own read-only connection, so the
             duty map's SQL runs unedited and sees only rows on or after the floor. The setting aaj.from moves the day.
  NO_HOLD    see there: the second guard, for work no view catches.
  OWNER_DROP the two tables of the OWNER'S OWN lines that he also ruled off for September (the clinic money flags, the
             physiotherapy days); his other lines stay on S487's floor (01-Sep), so nothing he must still close is hidden.
  SEPT       September, for him only: five things, each asked of the unfloored database with a date before the floor.
  LOGINS     a login that works another list (the desk's two people and its shared login work the Reception list).
"""
VERSION = "S493 seed 1"
FLOOR_DEFAULT = "2026-10-01"

FLOOR = {
    "clinic_day_revenue": "business_date",       # the counter sheet, the morning match's first pass
    "clinic_money_flag": "business_date",        # the morning match's flags
    "clinic_money_day": "business_date",         # the checker's check of a matched day
    "clinic_physio_day": "business_date",        # the physiotherapy days
    "day_entry": "business_date",                # the pharmacy day (Bhati's sale check, Darpan's cash)
    "blood_order": "day",                        # blood tests with no report
    "slip": "day",                               # X-ray slips with no photo
    "xray_filing": "CASE WHEN day <> '' THEN day ELSE substr(planned_at, 1, 10) END",   # X-ray files with no clinic ID
    "stock_spot_check": "business_date",         # the returns desk: shelf counts
    "identity_dispute": "business_date",         # the returns desk: name / ID
    "stock_spot_roster": "day",                  # Darpan's spot count
    "mi_bill_chain": "day",                      # a gap in Marg's bill numbers
    "stock_voucher_line": "substr(made_at, 1, 10)",   # the count's vouchers
    "slip_adjust": "substr(made_at, 1, 10)",          # a slip's discount / free / cancel waiting for a pass
    "supplier_msg": "substr(queued_at, 1, 10)",       # a supplier's payment message not sent
    "purchase_order_line": "substr(arrived_at, 1, 10)",   # goods arrived, bill not in Marg
    "order_sheet_line": "COALESCE(reorder_day, line_date)",   # a medicine to order
    "amir_claim": "substr(raised_at, 1, 10)",         # a claim on a supplier
    "claim_line": "substr(raised_at, 1, 10)",         # a count shortage to answer
    "export_watch": "day",                            # the purchase pair not exported
    "purchase_salt_task": "substr(done_at, 1, 10)",   # salt corrections waiting for the salt-wise list
    "stock_count_plan": "CASE WHEN status = 'picked' THEN substr(picked_at, 1, 10) ELSE due_from END",   # the full count's Sunday
}
# NOT UNDER A VIEW, ON PURPOSE: purchase_order and purchase_bill. Another duty asks of them 'is this already done?' (an order
# drafted, a bill come), and a view would hide a 30-Sep answer to a 2-Oct question -- it would MAKE work. The two duties that
# list them are floored in their own SQL instead:
# REWRITE  duty id -> (the exact piece of the duty map's SQL, what it becomes; '{floor}' is the floor's day). If the piece
#          is not in the map's SQL exactly once (the map has moved), the duty is UNREAD -- never shown unfloored.
REWRITE = {
    "reception.order_arrival": ("WHERE o.status = 'sent' AND", "WHERE o.status = 'sent' AND substr(o.created_at, 1, 10) >= '{floor}' AND"),
    "amir.bills_answer": ("AND b.bill_date >= '2026-09-01' AND", "AND b.bill_date >= '{floor}' AND"),
}
FIRST_OF = {"clinic_day_revenue": ("clinic_register_day", "business_date")}   # a day is a counter-sheet duty only since the sheet exists (S487)
OWNER_DROP = ("clinic_money_flag", "clinic_physio_day")

DUE = {
    # The map asks for every unanswered roster row up to today. The roster carries an unanswered item into the next
    # roster and never closes the old row, so that count cannot reach zero. The job is TODAY'S count: today's roster.
    "darpan.spot_count": "SELECT COUNT(*) AS n, MIN(day) AS since FROM stock_spot_roster WHERE answered_at IS NULL AND day = date('now','localtime')",
}

# AND WHERE NO VIEW CATCHES IT: a line whose oldest piece of work is dated before the floor is HELD BACK from staff (his panel
# says so) -- except these, whose job is yesterday's, today's or this month's by its nature however far back the first gap
# lies (the day they carry is where a gap began, or the first of the month -- not the day of a piece of old work).
NO_HOLD = ("shavez.sale_report", "shavez.closing_stock", "bhati.availability", "shavez.month_reports")

LOGINS = {"alisha": "reception", "shivani": "reception", "reception": "reception"}
VIEW_AS = {"reception": "alisha"}             # whose eyes the owner borrows to see a shared list

ENGINE = {'alisha.counter_sheet': {'door': '/finance/clinic/register/{since}'},
 'rec.docterz_morning': {'how': 'Reception PC par Docterz se report nikaliye. Wo apne aap server par chali jaati hai. Follow-up log: Docterz jo date apne aap dikhata hai (aaj se ek mahina) wahi rehne dijiye aur export kijiye -- date badalne ki zaroorat nahin.',   # S507
                         'src': ['reception.docterz_consultation', 'reception.docterz_followup']},
 'rec.match': {'door': '/finance/clinic/match/{since}', 'src': ['alisha.match_first_pass', 'alisha.match_flags']},
 'reception.night_counter_sheet': {'door': '/finance/clinic/register/{since}', 'how': 'Raat ko rah jaaye to kal subah bhar dijiye.'},
 'reception.night_exports': {'how': 'Follow-up log: Docterz jo date apne aap dikhata hai (aaj se ek mahina) wahi rehne dijiye aur export kijiye -- date badalne ki zaroorat nahin. Raat ko rah jaaye to kal subah yahi pehla kaam hoga.'},   # S507
 'shavez.docterz_watch': {'how': 'Reception se dono report abhi nikalwaiye.',
                          'src': ['reception.docterz_consultation', 'reception.docterz_followup']},
 'shavez.match_check': {'door': '/finance/clinic/match/{since}'}}

PEOPLE = [{'key': 'bhati',
  'pos': 1,
  'name': 'Bhati',
  'who': '',
  'step': 1,
  'step_label': 'Turn on first',
  'on': True,
  'note': '',
  'lines': [{'id': 'bhati.availability',
             'hi': 'Aaj aayenge? Haan ya nahin bataiye',
             'en': 'Says whether he is coming today. Reception reads it.',
             'when': 'first',
             'on': True,
             'opens': 'Petty book'},
            {'id': 'bhati.sale_check',
             'hi': 'Sanjeevni ki bikri jaanchiye: Sahi hai ya Galti hai',
             'en': "Checks each pharmacy day against Darpan's paper and the Marg sheet.",
             'when': 'first',
             'on': True,
             'opens': 'Medical sale check'},
            {'id': 'bhati.physio_tick',
             'hi': 'Physiotherapy ka hisaab dekhiye: Theek hai',
             'en': "Ticks each physiotherapy day's figures that reception wrote.",
             'when': 'first',
             'on': True,
             'opens': 'Petty book'},
            {'id': 'bhati.petty_today',
             'hi': 'Aaj ka petty kharcha book mein likhiye, bill ki photo ke saath. Kharcha na hua ho to bhi Ho gaya dabaiye',
             'en': "Today's petty expenses are in the petty book, or there were none.",
             'when': 'day',
             'on': True,
             'opens': 'Petty book'},
            {'id': 'bhati.petty_cash_match',
             'hi': 'Haath ka petty cash book se milaiye',
             'en': 'Petty cash in hand agrees with the book.',
             'when': 'day',
             'on': True,
             'opens': 'Petty book'}]},
 {'key': 'sukhveer',
  'pos': 2,
  'name': 'Sukhveer',
  'who': '',
  'step': 1,
  'step_label': 'Turn on first',
  'on': True,
  'note': '',
  'lines': [{'id': 'sukhveer.blood_mail',
             'hi': "Blood report baaki hai: lab se mail karaiye, phir 'Mail kar diya' dabaiye",
             'en': 'Gets each pending blood report mailed by the lab.',
             'when': 'day',
             'on': True,
             'opens': 'Report baaki'}]},
 {'key': 'shavez',
  'pos': 3,
  'name': 'Shavez',
  'who': '',
  'step': 2,
  'step_label': 'Turn on second',
  'on': True,
  'note': '',
  'lines': [{'id': 'shavez.sale_report',
             'hi': 'Kal ki marg sale report nikaliye',
             'en': "Yesterday's bill-wise sale report from Marg, before sales start.",
             'when': 'first',
             'on': True,
             'opens': 'Aaj ki reports'},
            {'id': 'shavez.closing_stock',
             'hi': 'Kal ka marg closing stock Marg se nikaliye',
             'en': "Yesterday's closing stock from Marg.",
             'when': 'first',
             'on': True,
             'opens': 'Aaj ki reports'},
            {'id': 'shavez.match_check',
             'hi': 'Reception ka kal ka hisaab check kijiye',
             'en': 'Checks the day reception has matched. His check closes the day.',
             'when': 'first',
             'on': True,
             'opens': 'Morning match'},
            {'id': 'shavez.docterz_watch',
             'hi': 'Reception ki Docterz report nahin aayi: unse nikalwaiye',
             'en': "Reception's missed Docterz reports, shown to Shavez as a reminder.",
             'when': 'first',
             'on': True,
             'opens': 'Docterz Revenue',
             'why': "Reception's own job. Suggested off here so one job sits with one person."},
            {'id': 'shavez.staff_register_approve',
             'hi': 'Staff register: attendance / chhutti ki entry approve kijiye',
             'en': 'Approves the staff-register days reception entered.',
             'when': 'day',
             'on': True,
             'opens': 'Staff Register'},
            {'id': 'shavez.slip_adjust_check',
             'hi': 'Parchi par chhoot / free / cancel: dekh kar pass kijiye',
             'en': 'Slip discounts, free and cancellations waiting for his pass.',
             'when': 'comeup',
             'on': True,
             'opens': 'OPD & X-ray/Proc Slips'},
            {'id': 'shavez.bill_chain_gap',
             'hi': 'Bill number ki series tooti hai: likhe hue dinon ki sale report dobara nikaliye',
             'en': "A gap in Marg's bill numbers: re-export the sale report of the days named.",
             'when': 'comeup',
             'on': True,
             'opens': 'Aaj ki reports'},
            {'id': 'shavez.supplier_messages',
             'hi': "Supplier ko NEFT ka message nahin gaya: 'Bhejo' dabaiye",
             'en': "Backup: sends a supplier's NEFT message the reception phone did not send.",
             'when': 'comeup',
             'on': True,
             'opens': 'Vendor payments'},
            {'id': 'shavez.week_cheque_register', 'hi': 'Cheque register check kijiye', 'en': 'Cheque register checked.', 'when': 'week', 'on': True, 'opens': ''},
            {'id': 'shavez.week_purchase_orders',
             'hi': 'Purchase orders dekhiye: kaun se gaye, kaun se aaye, kaun se der se',
             'en': 'Purchase orders reviewed: sent, arrived, late.',
             'when': 'week',
             'on': True,
             'opens': 'Purchase orders'},
            {'id': 'shavez.week_slip_audit',
             'hi': 'Parchi ki haftewar jaanch padhiye, khule sawaal niptaiye',
             'en': 'Weekly slip audit read, open questions cleared.',
             'when': 'week',
             'on': True,
             'opens': 'OPD & X-ray/Proc Slips'},
            {'id': 'shavez.month_reports',
             'hi': 'Mahine ki do report nikaliye: Stock valuation aur Stock expiry (1 se 7 tareekh)',
             'en': '1st to 7th: Stock valuation and Stock expiry as on the last day of the month before.',
             'when': 'month',
             'on': True,
             'opens': 'Aaj ki reports'},
            {'id': 'shavez.mahine_ka_kaam',
             'hi': 'Mahine ka kaam: checklist poori kijiye',
             'en': 'The month-end checklist for the accountant pack.',
             'when': 'month',
             'on': True,
             'opens': 'Mahine ka kaam'}]},
 {'key': 'amir',
  'pos': 4,
  'name': 'Amir',
  'who': '',
  'step': 2,
  'step_label': 'Turn on second',
  'on': False,
  'note': '',
  'lines': [{'id': 'amir.purchase_exports',
             'hi': 'Purchase ki do report nikaliye: Item-detail aur Bill-wise (1 tareekh se aaj tak)',
             'en': 'On a day he comes: the purchase pair from Marg.',
             'when': 'first',
             'on': True,
             'opens': 'Amir ka kaam'},
            {'id': 'amir.bills_answer',
             'hi': 'Har purchase bill par jawab dijiye: Theek hai, ya kya galat hai',
             'en': 'Answers every purchase bill: correct, or what is wrong.',
             'when': 'day',
             'on': True,
             'opens': 'Amir ka kaam'},
            {'id': 'amir.arrival_bill_entry',
             'hi': 'Maal aa gaya hai: bill Marg mein daaliye',
             'en': 'Goods have arrived: keys the bill into Marg.',
             'when': 'comeup',
             'on': True,
             'opens': 'Amir ka kaam'},
            {'id': 'amir.count_vouchers',
             'hi': "Stock voucher Marg mein daaliye, phir 'entered' lagaiye",
             'en': "Enters the stock count's vouchers in Marg, stage by stage.",
             'when': 'comeup',
             'on': True,
             'opens': 'Amir ka kaam'},
            {'id': 'amir.rate_entry',
             'hi': 'Marg ke item master mein selling rate daaliye',
             'en': 'Puts a selling rate in Marg for an item that has none.',
             'when': 'comeup',
             'on': True,
             'opens': 'Amir ka kaam'},
            {'id': 'amir.salt_list',
             'hi': 'Salt wise item list Excel mein nikaliye',
             'en': 'After salt corrections: the salt-wise item list from Marg, as Excel.',
             'when': 'comeup',
             'on': True,
             'opens': 'Amir ka kaam'},
            {'id': 'amir.full_count_sunday',
             'hi': 'Poori stock ginti ke liye Sunday chuniye',
             'en': 'Picks a Sunday for the full stock count when one falls due.',
             'when': 'comeup',
             'on': True,
             'opens': 'Amir ka kaam'},
            {'id': 'amir.own_correction',
             'hi': 'Meri entry galat thi: Marg ki agli export ka intezaar',
             'en': "His own correction, waiting for Marg's next export.",
             'when': 'comeup',
             'on': False,
             'opens': 'Amir ka kaam',
             'why': 'A wait, not a job. Suggested off.'},
            {'id': 'amir.scan_files',
             'hi': 'Scan ho chuke bill dekhiye (chahein to file lijiye)',
             'en': 'Scanned bills Marg does not have yet. Optional for him.',
             'when': 'comeup',
             'on': False,
             'opens': 'Amir ka kaam',
             'why': 'Optional; nothing is asked of him. Suggested off.'}]},
 {'key': 'reception',
  'pos': 5,
  'name': 'Reception',
  'who': 'Alisha, Shivani',
  'step': 3,
  'step_label': 'Turn on third',
  'on': True,
  'note': '',
  'lines': [{'id': 'rec.docterz_morning',
             'hi': 'Kal ki Docterz report rah gayi hai: abhi nikaliye (Consultation aur Follow-up)',
             'en': "Yesterday's Docterz reports did not reach the server. The trackers and the revenue page wait on them.",
             'when': 'first',
             'on': True,
             'opens': 'Docterz Revenue',
             'why': 'Two lines today (one per report), joined into one job.'},
            {'id': 'alisha.counter_sheet',
             'hi': 'Kal ka counter sheet rah gaya hai: abhi bhariye (cash / UPI / card)',
             'en': "Yesterday's counter sheet was not filled at night.",
             'when': 'first',
             'on': True,
             'opens': 'Docterz daily collection'},
            {'id': 'rec.match',
             'hi': 'Morning match: kal ka hisaab milaiye, har flag ki wajah likhiye',
             'en': 'Morning match for yesterday, with a reason on each flag.',
             'when': 'day',
             'on': True,
             'opens': 'Morning match',
             'why': 'Two lines today (first pass, flags), joined into one job.'},
            {'id': 'reception.staff_register',
             'hi': 'Staff register: attendance / chhutti ki entry kijiye',
             'en': 'Enters attendance and leave days in the staff register.',
             'when': 'day',
             'on': True,
             'opens': 'Staff Register'},
            {'id': 'reception.medicine_orders',
             'hi': 'Dawa ka order kijiye apne app se',
             'en': "Orders medicines from Darpan's order sheet: WhatsApp or call, then 'Order ho gaya'.",
             'when': 'day',
             'on': True,
             'opens': 'Purchase orders'},
            {'id': 'alisha.xray_photo',
             'hi': 'X-ray photo baaki hai: folder mein daaliye',
             'en': 'Puts the X-ray photo of each X-ray slip in the folder.',
             'when': 'day',
             'on': True,
             'opens': 'Report baaki'},
            {'id': 'reception.order_arrival',
             'hi': 'Maal aaya hai: supplier ka bill scan kijiye',
             'en': "Goods have come: scans the supplier's bill.",
             'when': 'comeup',
             'on': True,
             'opens': 'Purchase orders'},
            {'id': 'reception.bill_scan',
             'hi': 'Bill scan karna baaki hai',
             'en': 'A bill received earlier still has no scan.',
             'when': 'comeup',
             'on': True,
             'opens': 'Purchase orders'},
            {'id': 'reception.scan_questions',
             'hi': 'Scan ka sawaal: photo dekh kar bataiye',
             'en': 'Answers a question about a scan, one at a time.',
             'when': 'comeup',
             'on': True,
             'opens': 'Purchase orders'},
            {'id': 'alisha.check_blood',
             'hi': 'Blood test likha tha, report nahin aayi: lab se mangwaiye',
             'en': 'A blood test with no lab report after 2 days.',
             'when': 'comeup',
             'on': True,
             'opens': 'Check karein'},
            {'id': 'alisha.check_xray_files',
             'hi': 'X-ray file ka clinic ID nahin mila: sahi ID lagaiye',
             'en': 'An X-ray picture the system could not place.',
             'when': 'comeup',
             'on': True,
             'opens': 'Check karein'},
            {'id': 'reception.night_exports',
             'hi': 'Jaane se pehle: aaj ki Docterz ki dono report nikaliye',
             'en': "Before leaving: today's two Docterz reports.",
             'when': 'night',
             'on': True,
             'opens': 'Docterz Revenue'},
            {'id': 'reception.night_counter_sheet',
             'hi': 'Jaane se pehle: aaj ka counter sheet bhariye (cash / UPI / card)',
             'en': "Before leaving: today's counter sheet.",
             'when': 'night',
             'on': True,
             'opens': 'Docterz daily collection'},
            {'id': 'reception.week_float',
             'hi': 'Chhutta (float) giniye aur Rs 2,500 poora kijiye',
             'en': 'Change float counted and topped up.',
             'when': 'week',
             'on': True,
             'opens': ''},
            {'id': 'reception.week_film_stock',
             'hi': 'X-ray film ka stock giniye (dono size)',
             'en': 'X-ray film stock counted, both sizes.',
             'when': 'week',
             'on': True,
             'opens': ''},
            {'id': 'reception.week_pathology_register',
             'hi': 'Pathology register ko Report baaki se milaiye',
             'en': 'Pathology register tallied against Report baaki.',
             'when': 'week',
             'on': True,
             'opens': 'Report baaki'},
            {'id': 'reception.month_new_register',
             'hi': 'Naya register 1 tareekh ko shuru kijiye',
             'en': 'New physical register started on the 1st.',
             'when': 'month',
             'on': True,
             'opens': ''}]},
 {'key': 'darpan',
  'pos': 6,
  'name': 'Darpan',
  'who': '',
  'step': 4,
  'step_label': 'Turn on last',
  'on': True,
  'note': '',
  'lines': [{'id': 'darpan.cash_handover',
             'hi': 'Kal ka cash: kitna diya aur kisko diya, likhiye',
             'en': "Each morning: yesterday's cash handed over, and to whom.",
             'when': 'first',
             'on': True,
             'opens': 'Kal ka hisaab'},
            {'id': 'darpan.spot_count',
             'hi': 'Aaj ki ginti: 2 item gin kar likhiye (Som / Budh / Shani)',
             'en': 'Spot count mornings (Mon / Wed / Sat): counts the items shown.',
             'when': 'first',
             'on': True,
             'opens': 'Stock milaan'},
            {'id': 'darpan.order_review',
             'hi': 'Aaj ka order dekhiye aur pakka kijiye',
             'en': 'Order days: looks at the order list and confirms it per supplier.',
             'when': 'first',
             'on': True,
             'opens': 'Kal ka hisaab',
             'why': 'Sleeps while ordering is on his own Marg sheet, as it is today.'},
            {'id': 'darpan.order_sheet',
             'hi': 'Order sheet TEXT mein dobara save kijiye (pichhli file nahin padhi gayi)',
             'en': 'His last order sheet could not be read: save it again as text.',
             'when': 'comeup',
             'on': True,
             'opens': 'Kal ka hisaab'},
            {'id': 'darpan.amir_claims',
             'hi': 'Amir ke claim: supplier se baat kijiye',
             'en': 'Chases the supplier for each claim Amir raised on a bill.',
             'when': 'comeup',
             'on': True,
             'opens': 'Kal ka hisaab'},
            {'id': 'darpan.count_claims',
             'hi': 'Bina bill? Har line ka jawab dijiye',
             'en': 'Answers each count shortage you marked to pursue.',
             'when': 'comeup',
             'on': True,
             'opens': 'Stock milaan'},
            {'id': 'darpan.count_sunday_yes',
             'hi': 'Amir ka chuna Sunday: Theek hai?',
             'en': 'Says yes or no to the Sunday Amir picked for the full count.',
             'when': 'comeup',
             'on': True,
             'opens': 'Stock milaan'},
            {'id': 'darpan.desk_shelf_counts',
             'hi': 'Vaapsi Desk: shelf gin kar bataiye',
             'en': 'Counts the shelf for a flagged return.',
             'when': 'comeup',
             'on': False,
             'opens': 'Vaapsi Desk',
             'why': 'Held off for now: the Vaapsi Desk page it opens still shows September. Switch it on when that page starts from 1 October.'},
            {'id': 'darpan.desk_identity',
             'hi': 'Vaapsi Desk: bill ka naam / ID sahi kijiye',
             'en': 'Settles a bill whose name and clinic ID disagree.',
             'when': 'comeup',
             'on': False,
             'opens': 'Vaapsi Desk',
             'why': 'Held off for now: the Vaapsi Desk page it opens still shows September. Switch it on when that page starts from 1 October.'}]}]

SEPT = [
    {"id": "sept.bill_gap", "en": "Bill gap of 8 and 9 Sep: one sale bill and one credit note are missing from the chain",
     "door": "/finance/reports/aaj", "tile": "Aaj ki reports",
     "sql": "SELECT COUNT(DISTINCT day) AS n, MIN(day) AS since FROM mi_bill_chain WHERE (gap_before <> '' OR gap_inside <> '') AND day < '{floor}'"},
    {"id": "sept.count_vouchers", "en": "Count vouchers of the September count (they stay inside Amir's own flow)",
     "door": "/finance/amir", "tile": "Amir ka kaam",
     "sql": "SELECT COUNT(*) AS n, MIN(made_at) AS since FROM (SELECT l.count_id, l.round_no, l.kind, l.batch_no, MIN(l.made_at) AS made_at "
            "FROM stock_voucher_line l GROUP BY l.count_id, l.round_no, l.kind, l.batch_no) b WHERE substr(b.made_at, 1, 10) < '{floor}' AND NOT EXISTS "
            "(SELECT 1 FROM stock_voucher_entered e WHERE e.count_id = b.count_id AND e.round_no = b.round_no AND e.kind = b.kind AND e.batch_no = b.batch_no "
            "AND TRIM(COALESCE(e.marg_voucher_no,'')) <> '' AND e.id = (SELECT MAX(e2.id) FROM stock_voucher_entered e2 WHERE e2.count_id = b.count_id "
            "AND e2.round_no = b.round_no AND e2.kind = b.kind AND e2.batch_no = b.batch_no))"},
    {"id": "sept.returns_ok", "en": "Counter returns waiting for your OK", "door": "/finance/approvals", "tile": "Sanjeevni Medicos", "duty": "manoj.returns_ok"},
    {"id": "sept.cash_received", "en": "Darpan's cash to mark received", "door": "/finance/darpan/kal", "tile": "Kal ka hisaab",
     "sql": "SELECT COUNT(*) AS n, MIN(business_date) AS since FROM darpan_kal_day WHERE handed_p IS NOT NULL AND received_at IS NULL AND business_date < '{floor}'"},
    {"id": "sept.purchases_final", "en": "September's purchases to finalise", "door": "/finance/purchase/page/hub", "tile": "Marg Purchases",
     "sql": "SELECT CASE WHEN EXISTS (SELECT 1 FROM purchase_month WHERE month = substr(date('{floor}','-1 day'), 1, 7) AND status = 'final') THEN 0 ELSE 1 END AS n, "
            "date('{floor}','-1 day','start of month') AS since"},
]
