#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_live_pins.py v1.3 -- rebuild the live-pin list FROM THE REGISTER.

    python gen_live_pins.py <KB_Register_vX.md> --manifest CANONICAL_MANIFEST.md \
           --session "S### close" -o live_pins_S###close.txt

One authored source (D202): the Register is edited, the pin list is generated, never hand-edited.

HOW IT READS THE REGISTER. Every "CURRENT LIVE FILE VERSIONS" section holds markdown tables whose first
column is a file and whose second column is its md5. The Register is written NEWEST FIRST, so the FIRST
time a path is seen scanning from the top is its current pin; later rows are history and are skipped.

A row whose md5 cell carries no hash at all -- "(kit deploy_kits\\...)", "pin pending", a prose note --
is emitted as BLIND, never as a pass. A row whose md5 cell carries only the customary 8-character
shorthand is emitted as SHORT: it is a real pin, but only the first 8 characters are known to this file,
so a checker must compare 8 characters and say so. Nothing here is ever invented or padded.

v1.3 (S240) rewrote the parser after v1.2 was lost from every store (OWED since S238).
"""
import argparse
import hashlib
import io
import os
import re
import sys

FULL = re.compile(r"\b([0-9a-f]{32})\b")
SHORT = re.compile(r"\b([0-9a-f]{8})\b")
SEC = re.compile(r"^#+\s*CURRENT LIVE FILE VERSIONS", re.I)
ROW = re.compile(r"^\|\s*(.+?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$")


def clean(cell):
    return re.sub(r"[`*]", "", cell).strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("register")
    ap.add_argument("--manifest", default="CANONICAL_MANIFEST.md")
    ap.add_argument("--session", required=True)
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()

    raw = io.open(a.register, "rb").read()
    src_md5 = hashlib.md5(raw).hexdigest()
    lines = raw.decode("utf-8").split("\n")

    inside = False
    seen, rows = set(), []
    for ln in lines:
        if SEC.match(ln):
            inside = True
            continue
        if inside and ln.startswith("## ") and not SEC.match(ln):
            inside = False
        if not inside:
            continue
        m = ROW.match(ln)
        if not m:
            continue
        path, md5cell, note = clean(m.group(1)), clean(m.group(2)), clean(m.group(3))
        if not path or path.lower() in ("file", "path") or set(path) <= set("-: "):
            continue
        if path in seen:
            continue                                   # newest first: the first row wins
        seen.add(path)
        f, s = FULL.search(md5cell), SHORT.search(md5cell)
        if f:
            kind, pin = "VPS", f.group(1)
        elif s:
            kind, pin = "SHORT", s.group(1)
        else:
            kind, pin = "BLIND", "-" * 32
        rows.append((kind, pin, path, note[:160]))

    man_pin = ""
    if os.path.exists(a.manifest):
        mt = io.open(a.manifest, encoding="utf-8", errors="replace").read()
        base = os.path.basename(a.register)[:-3]
        for mm in re.finditer(re.escape(base) + r"`?\s*\|[^|]*\|\s*`?([0-9a-f]{32})", mt):
            man_pin = mm.group(1)
            break

    out = ["# live_pins.txt -- generated by gen_live_pins.py v1.3",
           "# DO NOT HAND-EDIT the VPS rows. Change the Register, re-run the",
           "# generator. One authored source (D202).",
           "# source: %s" % os.path.basename(a.register),
           "# source_md5: %s" % src_md5,
           "# session: %s" % a.session,
           "# manifest: %s" % os.path.basename(a.manifest),
           "# manifest_current_register_pin: %s" % (man_pin or "(not found -- run after the manifest)"),
           "# register_pin_verified: %s" % ("yes" if man_pin == src_md5 else "no"),
           "# columns: kind <TAB> md5 <TAB> path-or-name <TAB> note",
           "#",
           "# VPS    = a full md5 read from the Register; hold the live file to it",
           "# SHORT  = a real pin the Register records in 8-character shorthand; compare 8, say so",
           "# BLIND  = no hash in the Register (kit reference, pin pending); NEVER counted as a pass",
           ""]
    for kind, pin, path, note in rows:
        out.append("%s\t%s\t%s\t%s" % (kind, pin, path, note))
    out.append("")
    out.append("# rows: %d (VPS %d, SHORT %d, BLIND %d)"
               % (len(rows), sum(1 for r in rows if r[0] == "VPS"),
                  sum(1 for r in rows if r[0] == "SHORT"),
                  sum(1 for r in rows if r[0] == "BLIND")))
    io.open(a.out, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print("%s : %d rows (VPS %d · SHORT %d · BLIND %d) from %s"
          % (a.out, len(rows), sum(1 for r in rows if r[0] == "VPS"),
             sum(1 for r in rows if r[0] == "SHORT"),
             sum(1 for r in rows if r[0] == "BLIND"), os.path.basename(a.register)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
