#!/bin/bash
# S224_INSTALL_ALL -- the five S224 kits, in order, each with its own guards and self-rollback.
# Stops at the first kit whose expected file is not in place afterwards. Re-runnable: a kit already
# installed is skipped by its own pin check.

say(){ printf "\n==================== %s ====================\n" "$1"; }
fail(){ printf "\n!! STOPPED at: %s -- nothing after it was touched. Send Claude this whole output.\n" "$1"; exit 1; }
git -C /root/deploy/repo fetch --depth 1 origin main && git -C /root/deploy/repo reset --hard origin/main || fail 'repo fetch'

say "purchases rev 5  (S224_MARG_PURCHASES)"
if [ "$(md5sum /root/finance/purchase_app.py 2>/dev/null | cut -c1-32)" = "6366edb5bb42797d31ce5d73b1cf6598" ]; then echo "already installed -- skipped"; else
git -C /root/deploy/repo fetch --depth 1 origin main && git -C /root/deploy/repo reset --hard origin/main && cd /root/deploy/repo/deploy_kits/S224_MARG_PURCHASES && md5sum -c SUMS.md5 --quiet && ([ -f /root/finance/purchase_app.py.bak_S224r1 ] || \cp /root/finance/purchase_app.py /root/finance/purchase_app.py.bak_S224r1) && ([ -f /root/finance/purchase_app.py.bak_S224r3 ] || \cp /root/finance/purchase_app.py /root/finance/purchase_app.py.bak_S224r3) && \cp purchase_app.py /root/finance/purchase_app.py && systemctl restart clinic-finance.service && sleep 3 && (systemctl is-active --quiet clinic-finance.service && echo "UP -- purchases rev 4 live" && curl -s localhost:8106/finance/purchase/api/healthz && echo && md5sum /root/finance/purchase_app.py || (echo "FINANCE DID NOT COME BACK -- ROLLING BACK TO REV 3 BY ITSELF"; \cp /root/finance/purchase_app.py.bak_S224r3 /root/finance/purchase_app.py; systemctl restart clinic-finance.service; sleep 4; systemctl is-active clinic-finance.service; md5sum /root/finance/purchase_app.py; journalctl -u clinic-finance.service -n 12 --no-pager | tail -12))
[ "$(md5sum /root/finance/purchase_app.py 2>/dev/null | cut -c1-32)" = "6366edb5bb42797d31ce5d73b1cf6598" ] || fail "purchases rev 5"
fi

say "diffs page by role  (S224_DIFFS_ROLE_FIX)"
if [ "$(md5sum /root/finance/stock_app.py 2>/dev/null | cut -c1-32)" = "a61af74a1be41b879771af8977d2d9a5" ]; then echo "already installed -- skipped"; else
git -C /root/deploy/repo fetch --depth 1 origin main && git -C /root/deploy/repo reset --hard origin/main && cd /root/deploy/repo/deploy_kits/S224_DIFFS_ROLE_FIX && md5sum -c SUMS.md5 --quiet && [ "$(md5sum /root/finance/stock_app.py | cut -c1-8)" = "4e929d0b" ] && [ "$(md5sum /root/finance/stock_diffs.html | cut -c1-8)" = "3f6a87b2" ] || { echo "REFUSED: kit sums or live pins do not match -- NOTHING CHANGED"; false; } && \cp /root/finance/stock_app.py /root/finance/stock_app.py.bak_S224diffsrole_$(date +%Y%m%d) && \cp /root/finance/stock_diffs.html /root/finance/stock_diffs.html.bak_S224diffsrole_$(date +%Y%m%d) && \cp stock_app.py stock_diffs.html /root/finance/ && (/root/wa/venv/bin/python3 -B -c "import py_compile;py_compile.compile('/root/finance/stock_app.py',doraise=True,cfile='/tmp/s224_diffs_check.pyc')" && systemctl restart clinic-finance.service && sleep 3 && systemctl is-active --quiet clinic-finance.service && echo "UP -- the diffs page now draws only the buttons your login may use" && md5sum /root/finance/stock_app.py /root/finance/stock_diffs.html || (echo "COMPILE FAILED OR SERVICE DID NOT COME BACK -- ROLLING BACK BY ITSELF"; \cp /root/finance/stock_app.py.bak_S224diffsrole_$(date +%Y%m%d) /root/finance/stock_app.py; \cp /root/finance/stock_diffs.html.bak_S224diffsrole_$(date +%Y%m%d) /root/finance/stock_diffs.html; systemctl restart clinic-finance.service; sleep 3; systemctl is-active clinic-finance.service; md5sum /root/finance/stock_app.py /root/finance/stock_diffs.html; journalctl -u clinic-finance.service -n 12 --no-pager)); rm -f /tmp/s224_diffs_check.pyc
[ "$(md5sum /root/finance/stock_app.py 2>/dev/null | cut -c1-32)" = "a61af74a1be41b879771af8977d2d9a5" ] || fail "diffs page by role"
fi

say "Docterz tile names  (S224_DOCTERZ_TILE_NAMES)"
if [ "$(md5sum /root/portal/portal.py 2>/dev/null | cut -c1-32)" = "d28038047d81abd290d58ed15f9a1482" ]; then echo "already installed -- skipped"; else
git -C /root/deploy/repo fetch --depth 1 origin main && git -C /root/deploy/repo reset --hard origin/main && cd /root/deploy/repo/deploy_kits/S224_DOCTERZ_TILE_NAMES && md5sum -c SUMS.md5 --quiet && \cp /root/portal/tile_grants.json /root/portal/tile_grants.json.bak_S224dz_$(date +%Y%m%d-%H%M%S) && \cp patch_portal_docterz_names_s224.py /root/portal/ && /root/wa/venv/bin/python3 -B /root/portal/patch_portal_docterz_names_s224.py 3530f637d620c225906f9c0113b1f0b0 && \cp tile_grants.json /root/portal/tile_grants.json && systemctl restart clinic-portal && sleep 3 && (systemctl is-active --quiet clinic-portal && echo "UP -- Docterz tiles renamed" && md5sum /root/portal/portal.py /root/portal/tile_grants.json || (echo "PORTAL DID NOT COME BACK -- ROLLING BACK BY ITSELF"; ls -t /root/portal/portal.py.bak_S224_dznames_* | head -1 | xargs -I{} \cp {} /root/portal/portal.py; ls -t /root/portal/tile_grants.json.bak_S224dz_* | head -1 | xargs -I{} \cp {} /root/portal/tile_grants.json; systemctl restart clinic-portal; sleep 4; systemctl is-active clinic-portal; md5sum /root/portal/portal.py /root/portal/tile_grants.json; journalctl -u clinic-portal -n 12 --no-pager | tail -12))
[ "$(md5sum /root/portal/portal.py 2>/dev/null | cut -c1-32)" = "d28038047d81abd290d58ed15f9a1482" ] || fail "Docterz tile names"
fi

say "day revenue PDF + WhatsApp share  (S224_DAY_REVENUE_PDF)"
if [ "$(md5sum /root/finance/clinic_day_pdf.py 2>/dev/null | cut -c1-32)" = "518affe983e02a266f943bced48e9c35" ]; then echo "already installed -- skipped"; else
git -C /root/deploy/repo fetch --depth 1 origin main && git -C /root/deploy/repo reset --hard origin/main && cd /root/deploy/repo/deploy_kits/S224_DAY_REVENUE_PDF && md5sum -c SUMS.md5 --quiet && \cp clinic_day_pdf.py patch_finance_app_daypdf_s224.py walk_daypdf_gate_s224.py /root/finance/ && /root/wa/venv/bin/python3 -B /root/finance/patch_finance_app_daypdf_s224.py 44bf7b50d1e86af14e5bda79624fc8ca && systemctl restart clinic-finance.service && sleep 3 && (systemctl is-active --quiet clinic-finance.service && echo "UP -- day revenue PDF live" && curl -s -o /dev/null -w "clinic/share -> %{http_code}\n" localhost:8106/finance/clinic/share && md5sum /root/finance/finance_app.py /root/finance/clinic_day_pdf.py || (echo "FINANCE DID NOT COME BACK -- ROLLING BACK BY ITSELF"; \cp "$(ls -t /root/finance/finance_app.py.bak_S224_daypdf_* | head -1)" /root/finance/finance_app.py; systemctl restart clinic-finance.service; sleep 4; systemctl is-active clinic-finance.service; md5sum /root/finance/finance_app.py; journalctl -u clinic-finance.service -n 12 --no-pager | tail -12))
[ "$(md5sum /root/finance/clinic_day_pdf.py 2>/dev/null | cut -c1-32)" = "518affe983e02a266f943bced48e9c35" ] || fail "day revenue PDF + WhatsApp share"
fi

say "bank MPR status  (S224_BANK_MPR_STATUS)"
if [ "$(md5sum /root/finance/bank_mpr_status.py 2>/dev/null | cut -c1-32)" = "a0e740ce745230bcd7cada69e0428648" ]; then echo "already installed -- skipped"; else
git -C /root/deploy/repo fetch --depth 1 origin main && git -C /root/deploy/repo reset --hard origin/main && cd /root/deploy/repo/deploy_kits/S224_BANK_MPR_STATUS && md5sum -c SUMS.md5 --quiet && \cp bank_mpr_status.py patch_finance_app_mpr_status_s224.py walk_mpr_status_s224.py /root/finance/ && /root/wa/venv/bin/python3 -B /root/finance/patch_finance_app_mpr_status_s224.py $(md5sum /root/finance/finance_app.py | cut -c1-32) && systemctl restart clinic-finance.service && sleep 3 && (systemctl is-active --quiet clinic-finance.service && echo "UP -- MPR status live" && curl -s -o /dev/null -w "healthz %{http_code}\n" localhost:8106/finance/healthz && curl -s -o /dev/null -w "mpr route (302 = gate alive, page mounted) %{http_code}\n" localhost:8106/finance/clinic/bank/mpr/2026-09-03 && md5sum /root/finance/finance_app.py /root/finance/bank_mpr_status.py || (echo "SERVICE DID NOT COME BACK -- ROLLING BACK BY ITSELF"; ls -t /root/finance/finance_app.py.bak_S224_mprstatus_* | head -1 | xargs -I{} \cp {} /root/finance/finance_app.py; systemctl restart clinic-finance.service; sleep 4; systemctl is-active clinic-finance.service; md5sum /root/finance/finance_app.py; journalctl -u clinic-finance.service -n 12 --no-pager | tail -12))
[ "$(md5sum /root/finance/bank_mpr_status.py 2>/dev/null | cut -c1-32)" = "a0e740ce745230bcd7cada69e0428648" ] || fail "bank MPR status"
fi

say "ALL FIVE IN PLACE"
md5sum /root/finance/finance_app.py /root/finance/purchase_app.py /root/finance/stock_app.py /root/finance/stock_diffs.html /root/portal/portal.py /root/portal/tile_grants.json /root/finance/clinic_day_pdf.py /root/finance/bank_mpr_status.py
systemctl is-active clinic-finance.service clinic-portal
curl -s localhost:8106/finance/purchase/api/healthz; echo
curl -s -o /dev/null -w "clinic/share -> %{http_code}\n" localhost:8106/finance/clinic/share
